### Crear estudiante
POST http://localhost:8081/estudiantes
Content-Type: application/json

{
  "rut": "12345678-9",
  "nombre": "Juan Pérez",
  "correo": "juan.perez@email.com"
}
###
GET http://localhost:8081/estudiantes

###
GET http://localhost:8081/estudiantes/11111111-1